# Generated by Django 3.0.2 on 2020-02-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2shiptrack', '0002_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
