# Generated by Django 3.0.2 on 2020-02-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2shiptrack', '0015_auto_20200227_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lokasi',
            name='password',
        ),
        migrations.AddField(
            model_name='lokasiuser',
            name='nama',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
